routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;

Route::get('/', 'LandingController@index')->name('home');
Route::get ( '/redirect/{service}', 'SocialLoginController@redirect' );
Route::get ( '/callback/{service}', 'SocialLoginController@callback' );

Auth::routes();

Route::middleware(["auth", "lang"])->group(function () {
    Route::get('/register/wizard', 'WizardController@index');

    Route::post('/register/wizard', 'WizardController@store');

    Route::get('user/activation/{token}', 'Auth\LoginController@activateUser')->name('user.activate');


    Route::get('/volunteer/{username}', 'ProfileController@show')->name('profile.volunteer');
    Route::get('/volunteer/{username}/edit', 'ProfileController@edit')->name('profile.volunteer.edit');

    Route::get('/organization/{username}', 'OrganizationProfileController@show')->name('profile.organization');
    Route::get('/organization/{username}/edit', 'OrganizationProfileController@edit')->name('profile.organization.edit');

    Route::get('/search', "SearchController@show")->name("search");

    Route::get("/post/{post}", "PostController@show")->name("posts.show");

    Route::get("/event/create", "EventController@create");
    Route::get("/event/{event}", "EventController@show")->name('event.show');
});


// Localization
Route::get('/js/lang.js', function () {
    //$strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $strings[$name] = require $file;
        }

        //return $strings;
    //});

    header('Content-Type: text/javascript');
    echo('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');

app/Event.php
<?php

namespace App;

use App\Http\Resources\EventCollection;
use App\Http\Resources\UserCollection;
use App\MyModel as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

/**
 * @property Collection subscribers
 */
class Event extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'description', 'picture', "date_from", "date_to", "address", "city", "country"];

    protected $dates = ['date_from', 'date_to', 'deleted_at'];

    public function organization()
    {
        return $this->belongsTo(Organization::class);
    }

    public function subscribers()
    {
        return $this->belongsToMany(User::class);
    }

    public function getSubscribers()
    {
        return UserCollection::collection($this->subscribers);
    }

    public function getUrlAttribute()
    {
        return route('event.show', $this->id);
    }

    public function going(User $user) {
        return $this->subscribers()->attach($user);
    }

    public function leave(User $user) {
        return $this->subscribers()->detach($user);
    }

    public function isGoing()
    {
        return $this->subscribers()->where('id', Auth::user()->id)->get()->count() > 0;
    }

    public function getPictureAttribute($val)
    {
        if(is_null($val) || empty($val))
            return asset('images/event-default.jpg');
        return url($val);
    }

    public function getDateRangeAttribute()
    {
        return $this->date_from->eq($this->date_to) ?
            $this->date_from->toFormattedDateString() :
            $this->date_from->toFormattedDateString() . " " . trans("to") . " " . $this->date_to->toFormattedDateString();
    }

    /**
     * @param $target
     * @param $image_data
     * @param $extension
     */
    public function uploadImageEncoded($image_data, $extension)
    {

        $file_name = md5($this->username . time()) . "." . $extension;
        Storage::disk('events')->put($file_name, base64_decode($image_data));
        $uploaded_url = Storage::disk('events')->url($file_name);
        $this->update(['picture' => $uploaded_url]);
    }

    public function isOwner($user)
    {
        if ($user instanceof User)
            return $this->organization->user->id == $user->id;
        elseif ($user instanceof Organization)
            return $this->organization_id == $user->id;
        else
            throw new \InvalidArgumentException();
    }

    public static function search($s)
    {
        $orgs = Organization::where('name', 'LIKE', "%$s%")->pluck('id');

        $results = self::where("name", "LIKE", "%$s%")
            ->orWhere("city", "LIKE", "%$s%")
            ->orWhere("country", "LIKE", "%$s%")
            ->orWhere("address", "LIKE", "%$s%")
            ->whereIn("organization_id", $orgs, "or")
            ->simplePaginate(15);
        return $results;
    }
}

app/Organization.php
<?php

namespace App;

use App\Http\Resources\OrganizationCollection;
use App\MyModel as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Organization extends Model
{
    use SoftDeletes;
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at', 'founded_date'];

    protected $fillable = ['name', 'founded_date', 'website', 'about', 'country', 'city', 'address'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function specialities()
    {
        return $this->belongsToMany(Speciality::class);
    }

    public function events()
    {
        return $this->hasMany(Event::class);
    }

    public function eventsCount()
    {
        return $this->hasMany(Event::class)->count();
    }

    public function getFullNameAttribute()
    {
        return $this->name;
    }

    public function getProfilePictureAttribute($val)
    {
        return !is_null($val) ? $val : asset("images/default-avatar.jpg");
    }

    public function getCoverPictureAttribute($val)
    {
        return !is_null($val) ? $val : asset("images/default-cover.jpg");
    }

    public function getProfileUrlAttribute()
    {
        return route("profile.organization", ["username" => $this->user->username]);
    }

    public static function search($s)
    {
        $results = self::where("name", "LIKE", "%$s%")
            ->simplePaginate(15);
        return $results;
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <main>
        <?php /** @var \App\Volunteer $volunteer */ ?>

        <div class="container pt-md-4">
            <div class="row">
                <div class="col-md-3 d-none d-md-block">
                    @include('layouts.mainSidebar')
                </div>
                <div class="col-md-7">
                    <home-tabs></home-tabs>
                </div>
                <div class="col-md-2">
                    <div class="sidebar-home-right sidebar-sticky">
                        <div class="d-none d-md-block">
                            <small class="text-muted"><b>Suggestions</b></small>
                            <div class="suggestion-item demo">

                            </div>
                            <div class="suggestion-item demo">

                            </div>
                            <hr>
                        </div>
                        <div class="mt-4">
                            <small style="font-size: 0.65rem;" class="text-muted"><b>All rights reserved &copy; SVW
                                    2018</b>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/landing.blade.php
@extends('layouts.app')

@section('content')
    <main class="landing-page image-container">
        <div class="filter"></div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6 d-none d-md-block mx-auto">
                    <div class="landing-message">
                        <span class="typed"></span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-5 col-12 mx-auto">
                    <div class="card card-register">
                        <h3 class="card-title text-center">Register</h3>
                        <social-buttons style="margin: 1rem 0 -0.9rem;"></social-buttons>
                        <div class="division">
                            <div class="line l"></div>
                            <span>or</span>
                            <div class="line r"></div>
                        </div>
                        <form class="register-form" action="{{ route('register') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group{{ $errors->has('register_email') ? " has-danger" : "" }}">
                                <label>Email</label>
                                <input type="text"
                                       class="form-control{{ $errors->has('register_email') ? " form-control-danger" : "" }}"
                                       placeholder="Email"
                                       name="register_email" id="email" value="{{ old('register_email') }}">
                                @if ($errors->has('register_email'))
                                    <div class="form-control-feedback">{{ $errors->first('register_email') }}</div>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('register_username') ? " has-danger" : "" }}">
                                <label>Username</label>
                                <input type="text"
                                       class="form-control{{ $errors->has('register_username') ? " form-control-danger" : "" }}"
                                       placeholder="Username"
                                       name="register_username" id="username" value="{{ old('register_username') }}">
                                @if ($errors->has('register_username'))
                                    <div class="form-control-feedback">{{ $errors->first('register_username') }}</div>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('register_password') ? " has-danger" : "" }}">
                                <label>Password</label>
                                <input type="password"
                                       class="form-control{{ $errors->has('register_password') ? " form-control-danger" : "" }}"
                                       placeholder="Password"
                                       name="register_password" id="password">
                                @if ($errors->has('register_password'))
                                    <div class="form-control-feedback">{{ $errors->first('register_password') }}</div>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('register_password_confirmation') ? " has-danger" : "" }}">
                                <label>Confirm Password</label>
                                <input type="password"
                                       class="form-control{{ $errors->has('register_password_confirmation') ? " form-control-danger" : "" }}"
                                       placeholder="Confirm Password"
                                       name="register_password_confirmation" id="password_confirmation">
                                @if ($errors->has('register_password_confirmation'))
                                    <div class="form-control-feedback">{{ $errors->first('register_password_confirmation') }}</div>
                                @endif
                            </div>
                            <button class="btn btn-primary btn-block btn-round font-weight-bold"><i class="fa fa-user-plus"></i> Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/search-new.blade.php
@extends("layouts.app")

@section("content")
    <main class="search-page">
        @if(!empty($s))
            <div class="sub-heading">
                <div class="container">
                    <h3>@lang("Results for ") {{ $s }}</h3>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="d-md-none">
                            <a data-toggle="collapse" href="#searchToolsCollapse" role="button" aria-expanded="false"
                               aria-controls="searchToolsCollapse" class="btn btn-light"><i class="fa fa-filter"></i>
                                Search Filters</a>
                            <div class="collapse mt-2" id="searchToolsCollapse">
                                <b>Search for:</b>
                                <div class="nav nav-pills nav-pills-warning flex-column" id="searchTabs">

                                    {{--<a class="nav-item nav-link {{ $type == "all" ? "active" : "" }}"--}}
                                    {{--id="pills-all-tab"--}}
                                    {{--href="{{ route("search",["s"=>$s, "type"=>"all"]) }}"> @lang("All")</a>--}}

                                    <a class="nav-item nav-link {{ $type == "volunteer" ? "active" : "" }}"
                                       id="pills-volunteers-tab"
                                       href="{{ route("search",["s"=>$s, "type"=>"volunteer"]) }}"><i
                                                class="fa fa-user-circle"></i> @lang("Volunteers")</a>

                                    <a class="nav-item nav-link {{ $type == "event" ? "active" : "" }}"
                                       id="pills-events-tab"
                                       href="{{ route("search",["s"=>$s, "type"=>"event"]) }}"><i
                                                class="fa fa-calendar-alt"></i> @lang("Events")</a>

                                    <a class="nav-item nav-link {{ $type == "organization" ? "active" : "" }}"
                                       id="pills-organizations-tab"
                                       href="{{ route("search",["s"=>$s, "type"=>"organization"]) }}"><i
                                                class="fa fa-building"></i> @lang("Organizations")</a>
                                </div>
                            </div>
                        </div>
                        <div class="d-none d-md-block">
                            <small class="text-muted font-weight-bold">@lang("Search Tools")</small>
                            <hr>
                            <nav>
                                <div class="nav nav-pills nav-pills-warning flex-column" id="searchTabs">

                                    {{--<a class="nav-item nav-link {{ $type == "all" ? "active" : "" }}"--}}
                                    {{--id="pills-all-tab"--}}
                                    {{--href="{{ route("search",["s"=>$s, "type"=>"all"]) }}"> @lang("All")</a>--}}

                                    <a class="nav-item nav-link {{ $type == "volunteer" ? "active" : "" }}"
                                       id="pills-volunteers-tab"
                                       href="{{ route("search",["s"=>$s, "type"=>"volunteer"]) }}"><i
                                                class="fa fa-user-circle"></i> @lang("Volunteers")</a>

                                    <a class="nav-item nav-link {{ $type == "event" ? "active" : "" }}"
                                       id="pills-events-tab"
                                       href="{{ route("search",["s"=>$s, "type"=>"event"]) }}"><i
                                                class="fa fa-calendar-alt"></i> @lang("Events")</a>

                                    <a class="nav-item nav-link {{ $type == "organization" ? "active" : "" }}"
                                       id="pills-organizations-tab"
                                       href="{{ route("search",["s"=>$s, "type"=>"organization"]) }}"><i
                                                class="fa fa-building"></i> @lang("Organizations")</a>
                                </div>
                            </nav>
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <div class="search-results">
                            @if(isset($results['volunteers']) || isset($results['organizations']) || isset($results['events']))
                                <b class="text-muted">Volunteers Results:</b>
                                <search-results type="volunteer" :results="{{ $results['volunteers']->toJson() }}"></search-results>
                                {!! $results['volunteers']->appends(['s' => $s, 'type'=>$type])->links() !!}

                                <hr>
                                <b class="text-muted">Organizations Results:</b>
                                <search-results type="organization" :results="{{ $results['organizations']->toJson() }}"></search-results>
                                {!! $results['organizations']->appends(['s' => $s, 'type'=>$type])->links() !!}

                                <hr>
                                <b class="text-muted">Events Results:</b>
                                <search-results type="event" :results="{{ $results['events']->toJson() }}"></search-results>
                                {!! $results['events']->appends(['s' => $s, 'type'=>$type])->links() !!}

                            @else
                                <search-results type="{{ $type }}" :results="{{ json_encode($results->toArray()['data']) }}"></search-results>
                                {!! $results->appends(['s' => $s, 'type'=>$type])->links() !!}
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        @else
            <list-message>Please enter search term above</list-message>
        @endif
    </main>
@endsection

resources/views/search.blade.php
@extends("layouts.app")

@section("content")
    <main class="search-page">
        <div class="sub-heading">
            <div class="container">
                <h3>@lang("Results for ") {{ $s }}</h3>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <small class="text-muted font-weight-bold">@lang("Search Tools")</small>
                    <hr>
                    <nav>
                        <div class="nav nav-pills nav-pills-warning flex-column" id="searchTabs">

                            <a class="nav-item nav-link {{ $type == "volunteer" ? "active" : "" }}"
                               id="pills-volunteers-tab"
                               href="{{ route("search",["s"=>$s, "type"=>"volunteer"]) }}"><i
                                        class="fa fa-user-circle"></i> @lang("Volunteers")</a>

                            <a class="nav-item nav-link {{ $type == "event" ? "active" : "" }}" id="pills-events-tab"
                               href="{{ route("search",["s"=>$s, "type"=>"event"]) }}"><i
                                        class="fa fa-calendar-alt"></i> @lang("Events")</a>

                            <a class="nav-item nav-link {{ $type == "organization" ? "active" : "" }}"
                               id="pills-organizations-tab"
                               href="{{ route("search",["s"=>$s, "type"=>"organization"]) }}"><i
                                        class="fa fa-building"></i> @lang("Organizations")</a>
                        </div>
                    </nav>

                </div>
                <div class="col-sm-9">
                    <div class="search-results">
                        @if($results->count())
                            <ul class="row">
                                @if($type !== "event")
                                    @foreach($results as $result)
                                        <?php /** Volunteer $result */ ?>
                                        <li class="search-results__item col-sm-6">
                                            <a href="{{ $result->profile_url }}" class="card">
                                                <div class="card-body">
                                                    <div class="row">
                                                        <div class="col-sm-3 item-image">
                                                            <img src="{{ $result->user->profile_picture }}" alt="">
                                                        </div>
                                                        <div class="col-sm-9 item-content">
                                                            <h3>{{ $result->full_name }}</h3>
                                                            <p class="text-muted">{{ "@".$result->user['username'] }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    @endforeach
                                @else
                                    @foreach($results as $result)
                                        <?php /** Event $result */ ?>
                                        <li class="search-results__item event-result col-sm-6">
                                            <a href="{{ $result->url }}" class="card">
                                                <div class="card-body">
                                                    <div class="d-flex flex-column">
                                                        <div class="item-image">
                                                            <img src="{{ $result->picture }}" alt="">
                                                        </div>
                                                        <div class="item-content">
                                                            <h3>{{ $result->name }}</h3>
                                                            <p class="text-muted">
                                                                {{ __("By") }}: {{ $result->organization->name }}
                                                                <br>
                                                                {{ __("When") }}: {{ $result->date_range }}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    @endforeach
                                @endif
                            </ul>
                            {!! $results->appends(['s' => $s, 'type'=>$type])->links() !!}
                        @else
                            <normal-message class="mt-4">{{ __("No Results") }}</normal-message>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/wizard.blade.php
@extends("layouts.app")

@section('content')
    <main class="image-container">
        <div class=" set-full-height register-wizard">
            <div class="filter"></div>

            <!--   Big container   -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-8 mx-auto">

                        <!--      Wizard container        -->
                        <div class="wizard-container">

                            <div class="card wizard-card" id="wizardProfile">
                                <my-wizard :old="{{ json_encode(Session::getOldInput(),JSON_FORCE_OBJECT) }}"
                                           :countries="{{ json_encode($countries) }}"
                                           :user_id="{{ auth()->id() }}"></my-wizard>
                            </div>
                        </div> <!-- wizard container -->
                    </div>
                </div><!-- end row -->
            </div> <!--  big container -->
        </div>
    </main>
@endsection