routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;

Route::get('/', 'LandingController@index')->name('home');
Route::get ( '/redirect/{service}', 'SocialLoginController@redirect' );
Route::get ( '/callback/{service}', 'SocialLoginController@callback' );

Auth::routes();

Route::middleware(["auth", "lang"])->group(function () {
    Route::get('/register/wizard', 'WizardController@index');

    Route::post('/register/wizard', 'WizardController@store');

    Route::get('user/activation/{token}', 'Auth\LoginController@activateUser')->name('user.activate');


    Route::get('/volunteer/{username}', 'ProfileController@show')->name('profile.volunteer');
    Route::get('/volunteer/{username}/edit', 'ProfileController@edit')->name('profile.volunteer.edit');

    Route::get('/organization/{username}', 'OrganizationProfileController@show')->name('profile.organization');
    Route::get('/organization/{username}/edit', 'OrganizationProfileController@edit')->name('profile.organization.edit');

    Route::get('/search', "SearchController@show")->name("search");

    Route::get("/post/{post}", "PostController@show")->name("posts.show");

    Route::get("/event/create", "EventController@create");
    Route::get("/event/{event}", "EventController@show")->name('event.show');
});


// Localization
Route::get('/js/lang.js', function () {
    //$strings = Cache::rememberForever('lang.js', function () {
        $lang = config('app.locale');

        $files = glob(resource_path('lang/' . $lang . '/*.php'));
        $strings = [];

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $strings[$name] = require $file;
        }

        //return $strings;
    //});

    header('Content-Type: text/javascript');
    echo('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');

app/User.php
<?php

namespace App;

use App\Http\Resources\PostsCollection;
use Faker\Provider\Image;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\UploadedFile;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Laravel\Passport\HasApiTokens;

/**
 * @property string username
 * @property bool is_org
 * @property Organization organization
 * @property Volunteer volunteer
 * @property Collection[User] followers
 * @property Collection[User] following
 */
class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'is_org', 'provider', 'provider_id', 'profile_picture', 'cover_picture'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'is_org' => 'boolean',
    ];

    public function volunteer()
    {
        return $this->hasOne(Volunteer::class);
    }

    public function getProfileUrlAttribute()
    {
        if ($this->ready())
            if ($this->is_org)
                return $this->organization->profile_url;
            else
                return $this->volunteer->profile_url;
        return "#";
    }

    public function organization()
    {
        return $this->hasOne(Organization::class);
    }

    public function ready()
    {
        return !is_null($this->volunteer) || !is_null($this->organization);
    }

    public function accountType(string $type)
    {
        if ($type === "volunteer")
            $this->is_org = false;
        elseif ($type === "organization")
            $this->is_org = true;
        $this->save();
    }

    public function getNameAttribute()
    {
        if ($this->is_org && !is_null($this->organization))
            return $this->organization->name;
        elseif (!is_null($this->volunteer))
            return $this->volunteer->full_name;
        return $this->username;
    }

    public function getEditUrlAttribute()
    {
        if($this->is_org)
            return route("profile.organization.edit", ['username' => $this->username]);
        else
            return route("profile.volunteer.edit", ['username' => $this->username]);
    }

    public function following()
    {
        if ($this->is_org)
            return $this->belongsToMany(User::class, "followers", "follower_id", "following_id");
        else
            return $this->belongsToMany(User::class, "followers", "follower_id", "following_id")
                ->where("is_org", "!=", true);
    }

    public function followers()
    {
        return $this->belongsToMany(User::class, "followers", "following_id", "follower_id");
    }

    public function posts()
    {
        return $this->hasMany(Post::class)->orderBy("created_at", "desc");
    }

    public function likes()
    {
        return $this->belongsToMany(Post::class, "likes", "user_id", "post_id");
    }

    public function memberOf()
    {
        return $this->belongsToMany(User::class, "followers", "follower_id", "following_id")
            ->where("is_org", "=", true);
    }

    public function members() {
        $ids = $this->followers->where('is_org', false)->pluck('id')->toArray();
        return Volunteer::whereIn('user_id',$ids)->get();
    }

    public function memberships()
    {
        $ids = $this->memberOf()->pluck('users.id');
        return Organization::whereIn('user_id',$ids)->get();
    }

    public function likePost(Post $post)
    {
        $post->likes()->attach($this);
    }

    public function unlikePost(Post $post)
    {
        $post->likes()->detach($this);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function events()
    {
        return $this->belongsToMany(Event::class);
    }

    public function postsfeed()
    {
        $ids = DB::table('followers')->where('follower_id','=',$this->id)->pluck('following_id')->toArray();
        array_push($ids, $this->id);
        $posts = Post::whereIn("user_id",$ids)->latest()->get();
        return $posts;
    }

    public function eventsfeed()
    {
        $ids = $this->memberships()->pluck('id')->toArray();
        if($this->is_org)
            array_push($ids, $this->organization->id);
        $events = Event::whereIn("organization_id",$ids)->orderBy('date_from', 'asc')->get();
        return $events;
    }

    public function eventSchedule()
    {
        if ($this->is_org) {
            return $this->organization->events();
        }
        return $this->events();
    }

    public function getProfilePictureAttribute($val)
    {
        return !is_null($val) && $val !== "" ? $val : asset("images/default-avatar.jpg");
    }

    public function getCoverPictureAttribute($val)
    {
        return !is_null($val) && $val !== "" ? $val : asset("images/default-cover.jpg");
    }

    public function uploadImage($target, UploadedFile $file)
    {
        $fname = md5($this->username . time()) . '.' . $file->getClientOriginalExtension();
        Storage::putFileAs('public/avatars/' . $this->id . '/', $file, $fname);
        $uploadedUrl = Storage::disk("public")->url('/avatars/' . $this->id . '/' . $fname);
        switch ($target) {
            case "profile":
                $this->profile_picture = $uploadedUrl;
                $this->save();
                break;
            case "cover":
                $this->cover_picture = $uploadedUrl;
                $this->save();
                break;
        }
        return $uploadedUrl;
    }

    /**
     * @param $target
     * @param $image_data
     * @param $extension
     */
    public function uploadImageEncoded($target, $image_data, $extension)
    {
        $target = in_array($target, ['profile', 'cover']) ? $target : false;
        if (!$target)
            throw new \InvalidArgumentException("Target should be profile or cover picture");

        $file_name = 'avatars/' . $this->id . '/' . md5($this->username . time()) . "." . $extension;
        Storage::disk('public')->put($file_name, $image_data);
        $uploaded_url = Storage::disk('public')->url($file_name);

        switch ($target) {
            case "profile":
                $this->profile_picture = $uploaded_url;
                $this->save();
                break;
            case "cover":
                $this->cover_picture = $uploaded_url;
                $this->save();
                break;
        }
    }

    public function uploadImageFromUrl($target, $url)
    {
        $extension = '.jpg';
        $file_name = 'avatars/' . $this->id . '/' . md5($this->username . time()) . $extension;
        $fileContents = file_get_contents($url);
        Storage::disk('public')->put($file_name, $fileContents);
        $uploaded_url = Storage::disk('public')->url($file_name);

        switch ($target) {
            case "profile":
                $this->profile_picture = $uploaded_url;
                $this->save();
                break;
            case "cover":
                $this->cover_picture = $uploaded_url;
                $this->save();
                break;
        }
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    @yield("extraStyles")
</head>
<body class="{{ $body_classes ?? "" }}{{ isset($wizard) ?: " nav-fixed" }}">
@yield("after_body")

<div id="app">
    <nav class="navbar navbar-expand-md{{ isset($wizard) ? " transparent-bg" : " fixed-top" }}">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url('/') }}">Social<br>Volunteer<br>Work</a>

            <div class="d-flex" style="flex:1;">
                @auth
                    @if(!isset($wizard))
                        <form action="{{ route("search") }}" class="header-search-form d-none d-md-flex">
                            <input type="text" placeholder="Find Organization, Events, Volunteers ..."
                                   name="s" value="{{ $s ?? "" }}" class="form-control">
                            <input type="hidden" name="type" value="{{ $type ?? "volunteer" }}">
                            <button class="search-button" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    @endif
                @else
                    @if(!isset($login) || !$login)
                        <a href="/login" class="btn btn-sm btn-secondary d-md-none ml-auto"><i class="fa fa-key"></i> Login</a>
                    @endif
                @endauth

                @guest
                    <div class="navbar-nav ml-auto d-none d-md-block">
                        @if(!isset($login) || !$login)
                            <form class="form-login d-none d-md-flex" action="{{ route('login') }}" method="post">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <input type="text" class="form-control form-control-sm" name="login_email"
                                           placeholder="Email or Username" value="{{ old('login_email') }}">
                                    @if ($errors->has('login_email'))
                                        <div class="form-control-feedback">{{ $errors->first('login_email') }}</div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-sm" name="login_password"
                                           placeholder="Password">
                                    @if ($errors->has('login_password'))
                                        <div class="form-control-feedback">{{ $errors->first('login_password') }}</div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-sm btn-primary btn-round" type="submit"><i
                                                class="fa fa-key"></i>
                                        Login
                                    </button>
                                </div>
                                <a class='pink-text' style="font-size: 0.6rem;"
                                   href='{{ route('password.request') }}'><b>Forgot your<br>password?</b></a>
                            </form>
                        @endif
                    </div>
                @else
                    <div class="navbar-nav ml-auto ">
                        <!-- Right Side Of Navbar -->
                        <ul class="nav nav-pills header-navigation">
                            @if(!isset($isSearch))
                                <li class="nav-item d-md-none">
                                    <a class="nav-link px-3 search-mobile-toggle" href="/search">
                                        <i class="fa fa-search"></i>
                                    </a>
                                </li>
                            @endif
                            <li class="nav-item">
                                <a class="nav-link" href="{{{ auth()->user()->profile_url }}}">
                                    <img src="{{ auth()->user()->profile_picture }}" width="25"
                                         alt="{{{ auth()->user()->name }}}"> <span
                                            class="d-none d-md-inline">{{{ auth()->user()->name }}}</span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle px-3" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="{{ $current_user->edit_url }}"><i
                                                class="fa fa-cogs"></i> Profile Settings</a>
                                    <div class="dropdown-divider"></div>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();document.getElementById('logout-form').submit();"
                                    ><i class="fa fa-sign-out-alt"></i> Logout</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                @endguest

            </div>
        </div>
    </nav>
    <div class="search-mobile{{ isset($isSearch) ? " expanded in-search-page" : "" }}">
        <form action="{{ route("search") }}" class="header-search-form">
            <input type="text" placeholder="Find Organization, Events, Volunteers ..."
                   name="s" value="{{ $s ?? "" }}" class="form-control">
            <input type="hidden" name="type" value="{{ $type ?? "volunteer" }}">
            <button class="search-button" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>

    @yield('content')
    @yield("page_footer")
</div>

<!-- Scripts -->
<script src="{{ route("assets.lang") }}"></script>
<script src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/appWithFooter.blade.php
@extends("layouts.app")

@section("page_footer")
    <footer class="footer">
        <div class="container">
            <small class="text-muted text-bold">
                Social Volunteer Work &copy; 2018
            </small>
        </div>
    </footer>
@endsection

resources/views/layouts/mainSidebar.blade.php
<div class="home-sidebar-left sidebar-sticky">
    <div class="sidebar_user-details">
        <div class="sidebar_user-details__image">
            <div class="avatar-thumb large">
                <img src="{{ $current_user->profile_picture }}" alt="User">
            </div>
        </div>
        <div class="sidebar_user-details__text">
            <a href="{{ $current_user->profile_url }}">
                <div>{{ $current_user->name }}</div>
            </a>
            <small>{{ "@" . $current_user->username }}</small>
        </div>
    </div>
    <profile-numbers :is-org="{{ $current_user->is_org ? "true" : "false" }}" class="profile-numbers-sm"
                     :user-id="{{ $current_user->id }}"></profile-numbers>

    <hr>
    <div>
        <small><b class="text-muted">Your Events Schedule</b></small>
        <event-list size="tiny" :schedule="true"></event-list>
    </div>
    @if($current_user->is_org)
        <a href="/event/create">Create new event</a>
    @endif

</div>